# Minimum snapcast version for ALSA stream source is v0.21
# Currently Alpine 3.12 is pinned to snapcast v0.19 so we need to use Alpine edge
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge
WORKDIR /usr/src

RUN install_packages snapcast-client xxd alsa-utils

COPY start.sh .

CMD [ "/bin/bash", "/usr/src/start.sh" ]
